### ISSUE TITLE
LazyMC failes to boot because of glibc

### ISSUE THREAD

**Issue by XargonWan** [crbanman/papermc-lazymc-docker#7]
Greetings, I have the following library issue that prevents to start the server:

```
./lazymc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./lazymc)
./lazymc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./lazymc)
./lazymc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./lazymc)
sed: can't read lazymc.toml: No such file or directory
./lazymc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./lazymc)
./lazymc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./lazymc)
./lazymc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./lazymc)

```

My compose service:

```
  minecraft-server:
    image: crbanman/papermc-lazymc
    container_name: minecraft-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - EULA=TRUE
    volumes:
      - ../config/minecraft-server/data:/papermc
    ports:
      - 6009:25565
    restart: on-failure
```
